# Generated by Django 5.2.8 on 2025-11-07 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaginaLibro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='paginas_libro/')),
                ('numero', models.PositiveIntegerField()),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paginas', to='tienda.libro')),
            ],
            options={
                'ordering': ['numero'],
            },
        ),
    ]
